using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Medshop.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_name = 'Users'
    ) THEN
        CREATE TABLE public.""Users"" (
            ""UserIdPk"" integer GENERATED BY DEFAULT AS IDENTITY,
            ""Id"" uuid NOT NULL,
            ""FullName"" character varying(200) NOT NULL,
            ""Email"" character varying(200) NOT NULL,
            ""Mobile"" character varying(20) NOT NULL,
            ""PasswordHash"" text NOT NULL,
            ""Gender"" text,
            ""DateOfBirth"" timestamp with time zone,
            ""Address"" text,
            ""City"" text,
            ""State"" text,
            ""Country"" text,
            ""Pincode"" text,
            ""ProfileImage"" text,
            ""IsActive"" boolean NOT NULL,
            ""CreatedAt"" timestamp with time zone NOT NULL,
            ""UpdatedAt"" timestamp with time zone NOT NULL,
            CONSTRAINT ""PK_Users"" PRIMARY KEY (""UserIdPk"")
        );
        CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Users_Email"" ON public.""Users"" (""Email"");
        CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Users_Mobile"" ON public.""Users"" (""Mobile"");
        CREATE INDEX IF NOT EXISTS ""IX_Users_Id"" ON public.""Users"" (""Id"");
    ELSE
        IF NOT EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = 'Users'
              AND column_name = 'user_id_pk'
        ) THEN
            ALTER TABLE public.""Users"" ADD COLUMN ""user_id_pk"" integer GENERATED BY DEFAULT AS IDENTITY;
        END IF;

        IF EXISTS (
            SELECT 1
            FROM information_schema.table_constraints
            WHERE table_schema = 'public'
              AND table_name = 'Users'
              AND constraint_type = 'PRIMARY KEY'
        ) THEN
            ALTER TABLE public.""Users"" DROP CONSTRAINT ""PK_Users"";
        END IF;

        ALTER TABLE public.""Users"" ADD CONSTRAINT ""PK_Users"" PRIMARY KEY (""user_id_pk"");
        CREATE INDEX IF NOT EXISTS ""IX_Users_Id"" ON public.""Users"" (""Id"");
        CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Users_Email"" ON public.""Users"" (""Email"");
        CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Users_Mobile"" ON public.""Users"" (""Mobile"");
    END IF;
END
$$;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Users");
        }
    }
}
